# Form implementation generated from reading ui file 'c:\Users\Eleazar Leyte Zarate\Documents\Work_Space\Nueva_APP\modules\A_personal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(460, 750)
        Dialog.setMaximumSize(QtCore.QSize(460, 750))
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        Dialog.setStyleSheet("QDialog#Dialog{\n"
"background-color: qlineargradient(spread:pad, x1:0.488444, y1:0.392, x2:0.483241, y2:1, stop:0.266917 rgba(1, 59, 61, 255), stop:1 rgba(255, 255, 255, 244));}")
        self.Titulo = QtWidgets.QLabel(parent=Dialog)
        self.Titulo.setGeometry(QtCore.QRect(0, 0, 461, 71))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Titulo.setFont(font)
        self.Titulo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.Titulo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.Titulo.setAutoFillBackground(False)
        self.Titulo.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"color:rgba(239, 191, 188, 255);\n"
"")
        self.Titulo.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Titulo.setMidLineWidth(0)
        self.Titulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Titulo.setObjectName("Titulo")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 70, 461, 20))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\" rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.btn_guardar = QtWidgets.QPushButton(parent=Dialog)
        self.btn_guardar.setGeometry(QtCore.QRect(180, 660, 100, 30))
        self.btn_guardar.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_guardar.setFont(font)
        self.btn_guardar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_guardar.setStyleSheet("background-color: rgb(1, 59, 61);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.btn_guardar.setObjectName("btn_guardar")
        self.btn_regresar = QtWidgets.QPushButton(parent=Dialog)
        self.btn_regresar.setGeometry(QtCore.QRect(10, 710, 75, 23))
        self.btn_regresar.setSizeIncrement(QtCore.QSize(0, 0))
        self.btn_regresar.setBaseSize(QtCore.QSize(0, 0))
        self.btn_regresar.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 0, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.btn_regresar.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Eleazar Leyte Zarate\\Documents\\Work_Space\\Nueva_APP\\modules\\../assets/icons/arrow-left.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_regresar.setIcon(icon)
        self.btn_regresar.setObjectName("btn_regresar")
        self.layoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 600, 391, 38))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.area = QtWidgets.QLabel(parent=self.layoutWidget)
        self.area.setMinimumSize(QtCore.QSize(50, 34))
        self.area.setMaximumSize(QtCore.QSize(50, 34))
        self.area.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.area.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.area.setObjectName("area")
        self.horizontalLayout_5.addWidget(self.area)
        self.str_area = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.str_area.setMinimumSize(QtCore.QSize(110, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.str_area.setFont(font)
        self.str_area.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.str_area.setObjectName("str_area")
        self.str_area.addItem("")
        self.horizontalLayout_5.addWidget(self.str_area)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.cope = QtWidgets.QLabel(parent=self.layoutWidget)
        self.cope.setMinimumSize(QtCore.QSize(50, 34))
        self.cope.setMaximumSize(QtCore.QSize(50, 34))
        self.cope.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.cope.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.cope.setObjectName("cope")
        self.horizontalLayout_6.addWidget(self.cope)
        self.str_cope = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.str_cope.setMinimumSize(QtCore.QSize(110, 23))
        self.str_cope.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.str_cope.setObjectName("str_cope")
        self.str_cope.addItem("")
        self.horizontalLayout_6.addWidget(self.str_cope)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.layoutWidget1 = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(81, 101, 303, 374))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.apaterno = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.apaterno.setMinimumSize(QtCore.QSize(140, 23))
        self.apaterno.setMaximumSize(QtCore.QSize(140, 23))
        self.apaterno.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.apaterno.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.apaterno.setObjectName("apaterno")
        self.horizontalLayout_2.addWidget(self.apaterno)
        self.ln_apaterno = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.ln_apaterno.setMinimumSize(QtCore.QSize(150, 23))
        self.ln_apaterno.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.ln_apaterno.setText("")
        self.ln_apaterno.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ln_apaterno.setObjectName("ln_apaterno")
        self.horizontalLayout_2.addWidget(self.ln_apaterno)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.amaterno = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.amaterno.setMinimumSize(QtCore.QSize(140, 34))
        self.amaterno.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.amaterno.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.amaterno.setObjectName("amaterno")
        self.horizontalLayout_4.addWidget(self.amaterno)
        self.ln_materno = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.ln_materno.setMinimumSize(QtCore.QSize(150, 23))
        self.ln_materno.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.ln_materno.setText("")
        self.ln_materno.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ln_materno.setObjectName("ln_materno")
        self.horizontalLayout_4.addWidget(self.ln_materno)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nombre = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.nombre.setMinimumSize(QtCore.QSize(140, 34))
        self.nombre.setMaximumSize(QtCore.QSize(140, 34))
        self.nombre.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.nombre.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.nombre.setObjectName("nombre")
        self.horizontalLayout.addWidget(self.nombre)
        self.ln_nombre = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.ln_nombre.setMinimumSize(QtCore.QSize(150, 23))
        self.ln_nombre.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.ln_nombre.setText("")
        self.ln_nombre.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ln_nombre.setObjectName("ln_nombre")
        self.horizontalLayout.addWidget(self.ln_nombre)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(14, 13, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.expedientetecnico = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.expedientetecnico.setMinimumSize(QtCore.QSize(143, 34))
        self.expedientetecnico.setMaximumSize(QtCore.QSize(143, 34))
        self.expedientetecnico.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.expedientetecnico.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.expedientetecnico.setObjectName("expedientetecnico")
        self.horizontalLayout_3.addWidget(self.expedientetecnico)
        self.ln_expediente_c = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.ln_expediente_c.setMinimumSize(QtCore.QSize(150, 23))
        self.ln_expediente_c.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.ln_expediente_c.setText("")
        self.ln_expediente_c.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ln_expediente_c.setObjectName("ln_expediente_c")
        self.horizontalLayout_3.addWidget(self.ln_expediente_c)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.expediente_tecnico = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.expediente_tecnico.setMinimumSize(QtCore.QSize(143, 34))
        self.expediente_tecnico.setMaximumSize(QtCore.QSize(143, 34))
        self.expediente_tecnico.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.expediente_tecnico.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.expediente_tecnico.setObjectName("expediente_tecnico")
        self.horizontalLayout_13.addWidget(self.expediente_tecnico)
        self.ln_expediente_fo = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.ln_expediente_fo.setMinimumSize(QtCore.QSize(150, 23))
        self.ln_expediente_fo.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.ln_expediente_fo.setText("")
        self.ln_expediente_fo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ln_expediente_fo.setObjectName("ln_expediente_fo")
        self.horizontalLayout_13.addWidget(self.ln_expediente_fo)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        spacerItem2 = QtWidgets.QSpacerItem(14, 13, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.nss = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.nss.setMinimumSize(QtCore.QSize(140, 34))
        self.nss.setMaximumSize(QtCore.QSize(140, 34))
        self.nss.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.nss.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.nss.setObjectName("nss")
        self.horizontalLayout_9.addWidget(self.nss)
        self.ln_nss = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.ln_nss.setMinimumSize(QtCore.QSize(150, 23))
        self.ln_nss.setMaximumSize(QtCore.QSize(150, 23))
        self.ln_nss.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.ln_nss.setText("")
        self.ln_nss.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ln_nss.setObjectName("ln_nss")
        self.horizontalLayout_9.addWidget(self.ln_nss)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.rfc = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.rfc.setMinimumSize(QtCore.QSize(140, 34))
        self.rfc.setMaximumSize(QtCore.QSize(140, 34))
        self.rfc.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.rfc.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.rfc.setObjectName("rfc")
        self.horizontalLayout_10.addWidget(self.rfc)
        self.ln_rfc = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.ln_rfc.setMinimumSize(QtCore.QSize(150, 23))
        self.ln_rfc.setMaximumSize(QtCore.QSize(150, 23))
        self.ln_rfc.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.ln_rfc.setText("")
        self.ln_rfc.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ln_rfc.setObjectName("ln_rfc")
        self.horizontalLayout_10.addWidget(self.ln_rfc)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.layoutWidget2 = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(79, 480, 302, 117))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Direccin = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.Direccin.setMinimumSize(QtCore.QSize(300, 34))
        self.Direccin.setMaximumSize(QtCore.QSize(300, 34))
        self.Direccin.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.Direccin.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Direccin.setObjectName("Direccin")
        self.verticalLayout_2.addWidget(self.Direccin)
        self.ln_direccion = QtWidgets.QTextEdit(parent=self.layoutWidget2)
        self.ln_direccion.setMinimumSize(QtCore.QSize(300, 75))
        self.ln_direccion.setMaximumSize(QtCore.QSize(300, 75))
        self.ln_direccion.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.ln_direccion.setObjectName("ln_direccion")
        self.verticalLayout_2.addWidget(self.ln_direccion)
        self.nss.setBuddy(Dialog.Numero de Seguro Solcial:)
        self.rfc.setBuddy(Dialog.Numero de Seguro Solcial:)
        self.Direccin.setBuddy(Dialog.Numero de Seguro Solcial:)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Agregar personal operativo"))
        self.Titulo.setToolTip(_translate("Dialog", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Titulo.setWhatsThis(_translate("Dialog", "<html><head/><body><p align=\"center\">Comercilazadora LECE Comunicaciones</p></body></html>"))
        self.Titulo.setText(_translate("Dialog", "Comercilazadora LECE Comunicaciones"))
        self.label_2.setText(_translate("Dialog", "Alta de personal operativo"))
        self.btn_guardar.setText(_translate("Dialog", "Guardar"))
        self.area.setText(_translate("Dialog", "Área:"))
        self.str_area.setItemText(0, _translate("Dialog", "Seleccionar"))
        self.cope.setText(_translate("Dialog", "Cope:"))
        self.str_cope.setItemText(0, _translate("Dialog", "Seleccionar"))
        self.apaterno.setText(_translate("Dialog", "Apellido Paterno:"))
        self.ln_apaterno.setPlaceholderText(_translate("Dialog", "Ingresar apellido"))
        self.amaterno.setText(_translate("Dialog", "Apellido Materno:"))
        self.ln_materno.setPlaceholderText(_translate("Dialog", "Ingrsar apellido"))
        self.nombre.setText(_translate("Dialog", "Nombre(S):"))
        self.ln_nombre.setPlaceholderText(_translate("Dialog", "Ingresar nombre"))
        self.expedientetecnico.setText(_translate("Dialog", "E. Técnico Cobre:"))
        self.ln_expediente_c.setPlaceholderText(_translate("Dialog", "No. de Expediente"))
        self.expediente_tecnico.setText(_translate("Dialog", "E. Técnico F.O.:"))
        self.ln_expediente_fo.setPlaceholderText(_translate("Dialog", "No. de Expediente"))
        self.nss.setText(_translate("Dialog", "N.S. S.:"))
        self.ln_nss.setPlaceholderText(_translate("Dialog", "No. de Expediente"))
        self.rfc.setText(_translate("Dialog", "R.F.C.:"))
        self.ln_rfc.setPlaceholderText(_translate("Dialog", "No. de Expediente"))
        self.Direccin.setText(_translate("Dialog", "Dirección:"))
        self.ln_direccion.setPlaceholderText(_translate("Dialog", "Direccón"))
