# Form implementation generated from reading ui file 'c:\Users\Eleazar Leyte Zarate\Documents\Work_Space\Nueva_APP\modules\Login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(271, 325)
        login.setMaximumSize(QtCore.QSize(271, 325))
        login.setBaseSize(QtCore.QSize(2, 0))
        login.setStyleSheet("background-color: rgb(255, 255, 255);")
        login.setModal(False)
        self.logo = QtWidgets.QLabel(parent=login)
        self.logo.setGeometry(QtCore.QRect(90, 10, 100, 100))
        self.logo.setMaximumSize(QtCore.QSize(100, 100))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("c:\\Users\\Eleazar Leyte Zarate\\Documents\\Work_Space\\Nueva_APP\\modules\\../assets/images/Nuevo aspecto.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo.setWordWrap(False)
        self.logo.setObjectName("logo")
        self.label = QtWidgets.QLabel(parent=login)
        self.label.setGeometry(QtCore.QRect(80, 110, 121, 41))
        self.label.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.error_mesage = QtWidgets.QLabel(parent=login)
        self.error_mesage.setGeometry(QtCore.QRect(20, 250, 211, 21))
        self.error_mesage.setStyleSheet("color: rgb(255, 0, 0);")
        self.error_mesage.setScaledContents(True)
        self.error_mesage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.error_mesage.setObjectName("error_mesage")
        self.layoutWidget = QtWidgets.QWidget(parent=login)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 170, 251, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.usuario = QtWidgets.QLabel(parent=self.layoutWidget)
        self.usuario.setMinimumSize(QtCore.QSize(85, 3))
        self.usuario.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.usuario.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.usuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.usuario.setObjectName("usuario")
        self.horizontalLayout.addWidget(self.usuario)
        self.ln_user = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.ln_user.setMinimumSize(QtCore.QSize(150, 0))
        self.ln_user.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.ln_user.setText("")
        self.ln_user.setObjectName("ln_user")
        self.horizontalLayout.addWidget(self.ln_user)
        self.layoutWidget1 = QtWidgets.QWidget(parent=login)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 210, 251, 27))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pass = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.pass.setMinimumSize(QtCore.QSize(85, 0))
        self.pass.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.pass.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing)
        self.pass.setObjectName("pass")
        self.horizontalLayout_2.addWidget(self.pass)
        self.ln_password = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.ln_password.setMinimumSize(QtCore.QSize(150, 0))
        self.ln_password.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.ln_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.ln_password.setObjectName("ln_password")
        self.horizontalLayout_2.addWidget(self.ln_password)
        self.btn_acceder = QtWidgets.QPushButton(parent=login)
        self.btn_acceder.setGeometry(QtCore.QRect(80, 280, 100, 30))
        self.btn_acceder.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_acceder.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_acceder.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"border-radius: 10px\n"
"")
        self.btn_acceder.setObjectName("btn_acceder")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Iniciar Sesión"))
        self.label.setText(_translate("login", "Inicio de sesión"))
        self.error_mesage.setText(_translate("login", "TextLabel"))
        self.usuario.setText(_translate("login", "Usuario:"))
        self.ln_user.setPlaceholderText(_translate("login", "Ingrese su usuario"))
        self.pass.setText(_translate("login", "Contraseña:"))
        self.ln_password.setPlaceholderText(_translate("login", "Ingrese su contraseña"))
        self.btn_acceder.setText(_translate("login", "Acceder"))
