# Form implementation generated from reading ui file 'c:\Users\Eleazar Leyte Zarate\Documents\Work_Space\Nueva_APP\modules\Personal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Personal(object):
    def setupUi(self, Personal):
        Personal.setObjectName("Personal")
        Personal.resize(936, 694)
        Personal.setSizeIncrement(QtCore.QSize(0, 0))
        Personal.setBaseSize(QtCore.QSize(0, 8))
        Personal.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.488444, y1:0.392, x2:0.483241, y2:1, stop:0.266917 rgba(1, 59, 61, 255), stop:1 rgba(255, 255, 255, 244));}")
        self.centralwidget = QtWidgets.QWidget(parent=Personal)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Logo = QtWidgets.QLabel(parent=self.centralwidget)
        self.Logo.setMinimumSize(QtCore.QSize(0, 0))
        self.Logo.setMaximumSize(QtCore.QSize(100, 90))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap(":/recurso/Nuevo aspecto.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.horizontalLayout_2.addWidget(self.Logo)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.Titulo = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Titulo.setFont(font)
        self.Titulo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.Titulo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.Titulo.setAutoFillBackground(False)
        self.Titulo.setStyleSheet("font: 28pt \"Times New Roman\";\n"
"color:rgba(239, 191, 188, 255);\n"
"")
        self.Titulo.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Titulo.setMidLineWidth(0)
        self.Titulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Titulo.setObjectName("Titulo")
        self.horizontalLayout_2.addWidget(self.Titulo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_salir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_salir.setMinimumSize(QtCore.QSize(50, 23))
        self.btn_salir.setMaximumSize(QtCore.QSize(50, 23))
        self.btn_salir.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_salir.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 0, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.btn_salir.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Eleazar Leyte Zarate\\Documents\\Work_Space\\Nueva_APP\\modules\\../assets/icons/salir.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_salir.setIcon(icon)
        self.btn_salir.setObjectName("btn_salir")
        self.horizontalLayout_2.addWidget(self.btn_salir)
        spacerItem3 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(18, 15, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.btn_regresar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_regresar.setEnabled(True)
        self.btn_regresar.setMinimumSize(QtCore.QSize(50, 23))
        self.btn_regresar.setMaximumSize(QtCore.QSize(50, 23))
        self.btn_regresar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_regresar.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 0, 0);\n"
"color:rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.btn_regresar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\Eleazar Leyte Zarate\\Documents\\Work_Space\\Nueva_APP\\modules\\../assets/icons/atras bc.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_regresar.setIcon(icon1)
        self.btn_regresar.setObjectName("btn_regresar")
        self.horizontalLayout_5.addWidget(self.btn_regresar)
        spacerItem6 = QtWidgets.QSpacerItem(50, 25, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_agregar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_agregar.setMinimumSize(QtCore.QSize(100, 23))
        self.btn_agregar.setMaximumSize(QtCore.QSize(100, 23))
        self.btn_agregar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_agregar.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(1, 59, 61);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255);")
        self.btn_agregar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\Eleazar Leyte Zarate\\Documents\\Work_Space\\Nueva_APP\\modules\\../assets/icons/apersonal.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_agregar.setIcon(icon2)
        self.btn_agregar.setIconSize(QtCore.QSize(16, 16))
        self.btn_agregar.setAutoRepeatDelay(306)
        self.btn_agregar.setObjectName("btn_agregar")
        self.horizontalLayout_4.addWidget(self.btn_agregar)
        self.btn_eliminar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_eliminar.setMinimumSize(QtCore.QSize(100, 23))
        self.btn_eliminar.setMaximumSize(QtCore.QSize(100, 23))
        self.btn_eliminar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_eliminar.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(1, 59, 61);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255);")
        self.btn_eliminar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\Eleazar Leyte Zarate\\Documents\\Work_Space\\Nueva_APP\\modules\\../assets/icons/qpersonal.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eliminar.setIcon(icon3)
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.horizontalLayout_4.addWidget(self.btn_eliminar)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(40, 25, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(50, 23))
        self.label.setMaximumSize(QtCore.QSize(50, 23))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.str_area = QtWidgets.QComboBox(parent=self.centralwidget)
        self.str_area.setMinimumSize(QtCore.QSize(120, 23))
        self.str_area.setMaximumSize(QtCore.QSize(120, 23))
        self.str_area.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.str_area.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.str_area.setObjectName("str_area")
        self.str_area.addItem("")
        self.horizontalLayout.addWidget(self.str_area)
        spacerItem8 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 23))
        self.label_2.setMaximumSize(QtCore.QSize(50, 23))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.str_cope = QtWidgets.QComboBox(parent=self.centralwidget)
        self.str_cope.setMinimumSize(QtCore.QSize(120, 23))
        self.str_cope.setMaximumSize(QtCore.QSize(120, 23))
        self.str_cope.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.str_cope.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.str_cope.setObjectName("str_cope")
        self.str_cope.addItem("")
        self.horizontalLayout.addWidget(self.str_cope)
        spacerItem9 = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.btn_buscar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_buscar.setMinimumSize(QtCore.QSize(50, 23))
        self.btn_buscar.setMaximumSize(QtCore.QSize(50, 23))
        self.btn_buscar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_buscar.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(1, 59, 61);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255);\n"
"")
        self.btn_buscar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("c:\\Users\\Eleazar Leyte Zarate\\Documents\\Work_Space\\Nueva_APP\\modules\\../assets/icons/buscar.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_buscar.setIcon(icon4)
        self.btn_buscar.setObjectName("btn_buscar")
        self.horizontalLayout.addWidget(self.btn_buscar)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        spacerItem10 = QtWidgets.QSpacerItem(50, 25, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem10)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.tablapersonal = QtWidgets.QTableWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tablapersonal.setFont(font)
        self.tablapersonal.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.tablapersonal.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(1, 59, 61);")
        self.tablapersonal.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tablapersonal.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tablapersonal.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerPixel)
        self.tablapersonal.setObjectName("tablapersonal")
        self.tablapersonal.setColumnCount(0)
        self.tablapersonal.setRowCount(0)
        self.tablapersonal.horizontalHeader().setStretchLastSection(False)
        self.horizontalLayout_3.addWidget(self.tablapersonal)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem12)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem13 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_2.addItem(spacerItem13)
        self.btn_sincronizar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_sincronizar.setMinimumSize(QtCore.QSize(100, 23))
        self.btn_sincronizar.setMaximumSize(QtCore.QSize(100, 23))
        self.btn_sincronizar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_sincronizar.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";;\n"
"background-color: rgb(1, 59, 61);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom-color: rgb(239, 191, 188);\n"
"border-color: rgb(239, 191, 188);")
        self.btn_sincronizar.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("c:\\Users\\Eleazar Leyte Zarate\\Documents\\Work_Space\\Nueva_APP\\modules\\../assets/icons/sincronizar.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_sincronizar.setIcon(icon5)
        self.btn_sincronizar.setObjectName("btn_sincronizar")
        self.verticalLayout_2.addWidget(self.btn_sincronizar)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem14)
        self.btn_cargarexcel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_cargarexcel.setMinimumSize(QtCore.QSize(100, 23))
        self.btn_cargarexcel.setMaximumSize(QtCore.QSize(100, 23))
        self.btn_cargarexcel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_cargarexcel.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";;\n"
"background-color: rgb(1, 59, 61);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255);\n"
"border-bottom-color: rgb(239, 191, 188);\n"
"border-color: rgb(239, 191, 188);")
        self.btn_cargarexcel.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("c:\\Users\\Eleazar Leyte Zarate\\Documents\\Work_Space\\Nueva_APP\\modules\\../assets/icons/cargar.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_cargarexcel.setIcon(icon6)
        self.btn_cargarexcel.setObjectName("btn_cargarexcel")
        self.verticalLayout_2.addWidget(self.btn_cargarexcel)
        self.btn_descargarexcel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_descargarexcel.setMinimumSize(QtCore.QSize(100, 23))
        self.btn_descargarexcel.setMaximumSize(QtCore.QSize(100, 23))
        self.btn_descargarexcel.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_descargarexcel.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(1, 59, 61);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255);")
        self.btn_descargarexcel.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("c:\\Users\\Eleazar Leyte Zarate\\Documents\\Work_Space\\Nueva_APP\\modules\\../assets/icons/descarga.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_descargarexcel.setIcon(icon7)
        self.btn_descargarexcel.setObjectName("btn_descargarexcel")
        self.verticalLayout_2.addWidget(self.btn_descargarexcel)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem15)
        self.btn_guardar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_guardar.setMinimumSize(QtCore.QSize(100, 23))
        self.btn_guardar.setMaximumSize(QtCore.QSize(100, 23))
        self.btn_guardar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_guardar.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(1, 59, 61);\n"
"border-radius: 10px;\n"
"color:rgb(255, 255, 255);")
        self.btn_guardar.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("c:\\Users\\Eleazar Leyte Zarate\\Documents\\Work_Space\\Nueva_APP\\modules\\../assets/icons/Guardar.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_guardar.setIcon(icon8)
        self.btn_guardar.setObjectName("btn_guardar")
        self.verticalLayout_2.addWidget(self.btn_guardar)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem16)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem17 = QtWidgets.QSpacerItem(37, 20, QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem17)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        Personal.setCentralWidget(self.centralwidget)

        self.retranslateUi(Personal)
        QtCore.QMetaObject.connectSlotsByName(Personal)

    def retranslateUi(self, Personal):
        _translate = QtCore.QCoreApplication.translate
        Personal.setWindowTitle(_translate("Personal", "Personal"))
        self.Titulo.setToolTip(_translate("Personal", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Titulo.setWhatsThis(_translate("Personal", "<html><head/><body><p align=\"center\">Comercilazadora LECE Comunicaciones</p></body></html>"))
        self.Titulo.setText(_translate("Personal", "Comercilazadora LECE Comunicaciones"))
        self.btn_salir.setToolTip(_translate("Personal", "<html><head/><body><p align=\"center\">Salir</p></body></html>"))
        self.btn_regresar.setToolTip(_translate("Personal", "<html><head/><body><p align=\"center\">Regresar</p></body></html>"))
        self.btn_agregar.setToolTip(_translate("Personal", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ingresar personal</p></body></html>"))
        self.btn_eliminar.setToolTip(_translate("Personal", "<html><head/><body><p align=\"center\">Quitar personal</p></body></html>"))
        self.label.setText(_translate("Personal", "Área"))
        self.str_area.setItemText(0, _translate("Personal", "Seleccionar"))
        self.label_2.setText(_translate("Personal", "Cope"))
        self.str_cope.setItemText(0, _translate("Personal", "Seleccionar"))
        self.btn_buscar.setToolTip(_translate("Personal", "<html><head/><body><p align=\"center\">Buscar</p></body></html>"))
        self.btn_sincronizar.setToolTip(_translate("Personal", "<html><head/><body><p align=\"center\">Sincronizar.</p></body></html>"))
        self.btn_cargarexcel.setToolTip(_translate("Personal", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Cargar Layout.</p></body></html>"))
        self.btn_descargarexcel.setToolTip(_translate("Personal", "<html><head/><body><p align=\"center\">Descargar en formato Excel.</p></body></html>"))
        self.btn_guardar.setToolTip(_translate("Personal", "<html><head/><body><p align=\"center\">Guardar cambios.</p></body></html>"))
