# Form implementation generated from reading ui file 'c:\Users\Eleazar Leyte Zarate\Documents\Work_Space\Nueva_APP\modules\Pestaña 1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(362, 343)
        Menu.setMaximumSize(QtCore.QSize(362, 344))
        Menu.setStyleSheet("QDialog#Menu{\n"
"background-color: qlineargradient(spread:pad, x1:0.488444, y1:0.392, x2:0.483241, y2:1, stop:0.266917 rgba(1, 59, 61, 255), stop:1 rgba(255, 255, 255, 244));}")
        self.btn_personal = QtWidgets.QPushButton(parent=Menu)
        self.btn_personal.setGeometry(QtCore.QRect(120, 130, 121, 23))
        self.btn_personal.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_personal.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.btn_personal.setObjectName("btn_personal")
        self.btn_almacen = QtWidgets.QPushButton(parent=Menu)
        self.btn_almacen.setGeometry(QtCore.QRect(120, 180, 121, 23))
        self.btn_almacen.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_almacen.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.btn_almacen.setObjectName("btn_almacen")
        self.btn_produccion = QtWidgets.QPushButton(parent=Menu)
        self.btn_produccion.setGeometry(QtCore.QRect(120, 230, 121, 23))
        self.btn_produccion.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_produccion.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.btn_produccion.setObjectName("btn_produccion")
        self.btn_salir = QtWidgets.QPushButton(parent=Menu)
        self.btn_salir.setGeometry(QtCore.QRect(250, 280, 61, 23))
        self.btn_salir.setMinimumSize(QtCore.QSize(5, 0))
        self.btn_salir.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_salir.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px")
        self.btn_salir.setObjectName("btn_salir")
        self.Titulo = QtWidgets.QLabel(parent=Menu)
        self.Titulo.setGeometry(QtCore.QRect(0, 0, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Titulo.setFont(font)
        self.Titulo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.Titulo.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.Titulo.setAutoFillBackground(False)
        self.Titulo.setStyleSheet("font: 16pt \"Times New Roman\";\n"
"color:rgba(239, 191, 188, 255);\n"
"")
        self.Titulo.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.Titulo.setMidLineWidth(0)
        self.Titulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Titulo.setObjectName("Titulo")
        self.label = QtWidgets.QLabel(parent=Menu)
        self.label.setGeometry(QtCore.QRect(0, 70, 361, 20))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\" rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Ménu"))
        self.btn_personal.setText(_translate("Menu", "Personal"))
        self.btn_almacen.setText(_translate("Menu", "Almacén"))
        self.btn_produccion.setText(_translate("Menu", "Producción"))
        self.btn_salir.setText(_translate("Menu", "Salir"))
        self.Titulo.setToolTip(_translate("Menu", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.Titulo.setWhatsThis(_translate("Menu", "<html><head/><body><p align=\"center\">Comercilazadora LECE Comunicaciones</p></body></html>"))
        self.Titulo.setText(_translate("Menu", "Comercilazadora LECE Comunicaciones"))
        self.label.setText(_translate("Menu", "Seleccione una opción para continuar "))
