name: Auto Versioning
on:
  push:
    branches: [master]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set version
        run: |
          echo "$(date +'%Y.%-m.0')" > version.txt
          
      - name: Commit version
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-bump version"
          file_pattern: version.txt
